import { nextConfig } from '@rivora/eslint-config/next';

export default [
  ...nextConfig,
  // `next-env.d.ts` is generated by Next on every build and is not ours to fix.
  { ignores: ['.next/**', 'next-env.d.ts'] },
];
